### ISSUE TITLE
Clicking on edit butons from section preview causes an JS error

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/epsilon-framework#103]
![image](https://user-images.githubusercontent.com/113568/39301363-7ca78db4-4957-11e8-9a74-849c2d5d0cf6.png)

**Comment by ngabyn** [comment]
Se pare ca dupa ce am dezinstalat speed booster si-a revenit

**Comment by cristianraiber** [comment]
@ngabyn - dap, SPB muta JS-urile in footer, fara a respecta ordinea in care-au fost enqueued si/sau a dependintelor :) Acolo se pare ca script-urile main se initializeaza inaintea jQuery-ului.

**Comment by ngabyn** [comment]
@cristianraiber m-am gandit la asta si am dezactivat spb ca parca parca era noua eroarea :)
