### ISSUE TITLE
Typography control, default options

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/epsilon-framework#114]
Let's add a (clear) link on typography also, so we can reset the style itself to the original version.

![image](https://user-images.githubusercontent.com/113568/40785930-7453b082-64f2-11e8-9f75-1dba5d4f46cc.png)

**Comment by ngabyn** [comment]
- [ ] The link should be added at the end of the field label
- [ ] Momentan  cand se apasa pe Clear titlul valoarea din dropdown devine "" ar trebui schimbat in "Theme default"

**Comment by cristianraiber** [comment]
This has been implemented.
