### ISSUE TITLE
Hide Editor for pages built with Epsilon

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/epsilon-framework#130]
We should hide the tinymce editor for pages that are built with epsilon. Similar to what Elementor does :

---

![epsilon-page](https://user-images.githubusercontent.com/7580330/41410651-d219b96e-6fe2-11e8-9367-c2c1c7f903fe.png)

**Comment by cristianraiber** [comment]
The issue here being that if you've edited a page with Epsilon, go into the back-end and see all the HTML that Epsilon saves as back-up content, you might think editing said content is possible and will be reflected on the frontend.

However, that's not possible.

**Comment by cristianraiber** [comment]
related to: #69
