### ISSUE TITLE
Epsilon HTML UI experiments

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/epsilon-framework#132]
## Experiment 1
- when you expand a section, all the other sections get an opacity of `0.2`
- in this example I've reduced the padding on `.repeater-field` to `6px 0`
- I've removed the `.repeater-row-footer` class as I feel that's no longer needed since we have quick action links

---

![image](https://user-images.githubusercontent.com/7841556/41419017-b0f4f138-6ff9-11e8-9dcc-ebf0ed16e08a.png)

**Comment by cristianraiber** [comment]
- Label inline next to controls for all control types (similar to toggle switches)

![image](https://user-images.githubusercontent.com/7841556/41419544-fa7f7156-6ffa-11e8-9bfe-2b8d09dd2600.png)

**Comment by cristianraiber** [comment]
- Move tabs to the left, help icon to the right
- Section tab padding fixes
---

![image](https://user-images.githubusercontent.com/7841556/41419919-e56b0540-6ffb-11e8-8358-47c93cc3cb5c.png)

**Comment by cristianraiber** [comment]
- add pulsating effect on add section button 
```@keyframes pulse_animation {
  0% { transform: scale(1); }
  30% { transform: scale(1); }
  40% { transform: scale(1); }
  50% { transform: scale(1.05); }
  60% { transform: scale(1); }
  70% { transform: scale(1); }
  80% { transform: scale(1); }
  100% { transform: scale(1); }
}

.epsilon-pulse {
  animation-name: pulse_animation;
  animation-duration: 5000ms;
  transform-origin:70% 70%;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
}
```
- change button name from "Add Section" to "Add More Sections"
- change CSS to make it wider to: 

``` font-size: 14px;
  height: 32px;
  line-height: 30px;
  padding: 0 36px;```

![image](https://user-images.githubusercontent.com/7841556/41437373-e9cc6e68-702c-11e8-9dd6-4f779efa17de.png)

**Comment by ngabyn** [comment]
## Experiment 4

Expanding a section should move it to the top having 6px from the top, so you will benefit from the entire screen height:

![image](https://user-images.githubusercontent.com/113568/41468479-d270c13e-70b2-11e8-9478-fc3bf5acdf4a.png)
