### ISSUE TITLE
New Epsilon Field Type - Layout

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/epsilon-framework#134]
# Specs
We need a new control with maxim 8 options, you should be able to custom add options  and custom previews so it could be used in many cases, items should flow to the left there's not fixed number of items per row. It will be located in the Layout section tab.

Every layout should have an id like: **grid, masonry, frame, list, strip** 

Each layout should be able to determine the section to load a different template part:
section-portfolio-**portfolio_layout_id**.php

**Example:**
section-portfolio-**grid**.php
section-portfolio-**masonry**.php
section-portfolio-**frame**.php
section-portfolio-**list**.php
section-portfolio-**strip**.php

## Overall Look
![image](https://user-images.githubusercontent.com/113568/41495044-2508564a-7127-11e8-99fc-5dc7ee34be3d.png)

## Properties
Item size: 60x60px
Icon size: 50x50px

**Normal state:**
```
border-style: solid;
border-width: 1px;
border-color: rgb(219, 219, 219);
border-radius: 3px;
background-image: -moz-linear-gradient( 90deg, rgb(246,246,246) 0%, rgb(255,255,255) 100%);
background-image: -webkit-linear-gradient( 90deg, rgb(246,246,246) 0%, rgb(255,255,255) 100%);
background-image: -ms-linear-gradient( 90deg, rgb(246,246,246) 0%, rgb(255,255,255) 100%);
box-shadow: 0px 0px 4px 0px rgba(0, 0, 0, 0.06);
width: 58px;
height: 58px;
margin:6px 6px 0 0;
```

**Hover state:**
```
border-color: rgb(138, 144, 150);
background-image: -moz-linear-gradient( 90deg, rgb(246,246,246) 0%, rgb(255,255,255) 100%);
background-image: -webkit-linear-gradient( 90deg, rgb(246,246,246) 0%, rgb(255,255,255) 100%);
background-image: -ms-linear-gradient( 90deg, rgb(246,246,246) 0%, rgb(255,255,255) 100%);
box-shadow: 0px 0px 4px 0px rgba(0, 0, 0, 0.06),inset 0px 4px 0px 0px rgba(138, 144, 150, 0.004),inset 0px 2px 5px 0px rgba(0, 0, 0, 0.08);
```

**Active state:**
```
border-color: rgb(84, 161, 194);
background-image: -moz-linear-gradient( 90deg, rgb(246,246,246) 0%, rgb(255,255,255) 100%);
background-image: -webkit-linear-gradient( 90deg, rgb(246,246,246) 0%, rgb(255,255,255) 100%);
background-image: -ms-linear-gradient( 90deg, rgb(246,246,246) 0%, rgb(255,255,255) 100%);
box-shadow: 0px 0px 4px 0px rgba(0, 0, 0, 0.06),inset 0px 4px 0px 0px rgba(87, 167, 201, 0.004),inset 0px 2px 5px 0px rgba(0, 0, 0, 0.08);
```

## Extra details
It remains to be debated what can and can't be done.

**Comment by cristianraiber** [comment]
This should go in the "Layout" tab of a section that supports this new control.
