### ISSUE TITLE
Section parallax option is active while previewing in customizer regarding on/off 

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/epsilon-framework#139]

**Comment by cristianraiber** [comment]
Let's also post a scenario when this reacts like this. It's not happening at my end.

**Comment by ngabyn** [comment]
![parallax-section](https://user-images.githubusercontent.com/113568/41899459-2875fb00-7935-11e8-951b-22c00115cdfc.gif)

**Comment by cristianraiber** [comment]
Later edit: 

- turn parallax to ON
- turn parallax to OFF
- parallax effect is still there

I think this is happening because we're not getting the values using `get_theme_mod` on the frontend

**Comment by cristianraiber** [comment]
Not happening anymore.
