### ISSUE TITLE
How to off event refresh in customizer

### ISSUE THREAD

**Issue by himadree** [MachoThemes/epsilon-framework#146]
>  'transport'         => 'postMessage'

 not working in **fields** array

**Comment by cristianraiber** [comment]
Could you please detail your problem?

**Comment by himadree** [comment]
Is it possible to create a custom page like '**About page**' using Epsilon framework?
Now i created some custom page, after that when i update some content or image some thing like this ... the page content fully invisible but when i refresh page content appear. I tried using '**transport' => 'postMessage**' for stop customize refresh but it don't work.
How to use **'transport' => 'postMessage'** in Epsilon framework repeatable section?

**Comment by c0sm1n87** [comment]
Those are not individual fields in the customizer so transport doesn't work. You should add it to the actual field ( the customizer field that has the following type -> 'type' => 'epsilon-section-repeater'). 

However, you have to handle the live updating "logic" by yourself
