### ISSUE TITLE
Checking filesystem calls

### ISSUE THREAD

**Issue by justintadlock** [MachoThemes/epsilon-framework#37]
You have several calls to `$wp_filesystem->get_contents()`.  In all instances, the code doesn't check if the result is `false`.

For example, this is from your icon picker class:

```
$icons = $wp_filesystem->get_contents( $path );

return json_decode( $icons );
```

And, later in the Underscore template, you loop without checking if there's data to loop through:

```
<# _.each(data.icons, function(k, v){ #>
```

At some point, you need to verify that there are icons.  You can do this early or late.

Check the following files for issues:

* `classes/class-epsilon-color-scheme.php`
* `classes/class-epsilon-typography.php`
* `customizer/controls/class-epsilon-control-icon-picker.php`
* `customizer/controls/class-epsilon-control-repeater.php`
* `customizer/controls/class-epsilon-control-section-repeater.php`
* `customizer/controls/class-epsilon-control-typography.php`

**Comment by justintadlock** [comment]
The direct call to `file_get_contents()` will get flagged by Theme Check.  If `$wp_filesystem->get_contents( $path )` is not returning anything for you, you're probably not going to get it with `file_get_contents()` anyway.

I think there may have been a misunderstanding about what I was talking about above.  The extra code you have now was unnecessary and doesn't address the issue.

The point is that your JS template expects an array.  `false` is already returned by `$wp_filesystem->get_contents()` if it gets nothing.  So, you either need to make sure the return value is an array or check if you have a value in the JS template.

This could just be a matter of returning like so (or something like this):

```
$contents = $wp_filesystem->get_contents( $path );

return is_array( $contents ) ? $contents : array();
```

Or, in your templates, doing something like this:

```
<# if ( data.choices ) { #>
	<# _.each(data.choices, function(el) { #>
```

**Comment by justintadlock** [comment]
I'd just like to add that there's about 0.01% chance of this ever being a problem.  But, I like to code for that rare problem.

**Comment by c0sm1n87** [comment]
hey @justintadlock,

That extra code is related to another issue regarding the wp_filesystem function. On some servers ( I don`t exactly know the PHP Version or other server specs ),  that particular function would return false, while file_get_contents would work without any problems. 

There were only few cases in our support system, but I thought it's best I address it now. I`ll take a closer look and address the issue this week.
