### ISSUE TITLE
UX: Front page customizer sections

### ISSUE THREAD

**Issue by justintadlock** [MachoThemes/epsilon-framework#43]
Under the "Front Page" panel, the only section shown should be "Static Front Page" when the user hasn't yet set a page as a front page.  You should use the `active_callback` method to show/hide the other sections.

I'm not a huge fan of hiding all those sections though because users might not know they exist.  If you can find a way to make them grayed-out/unclickable until a user has chosen a front page, it'll give a clearer path for the user to follow.

That's one reason I'd love to see the core "Static Front Page" section shown at the top as the first section.  Choosing a front page is the first and arguably the most important step of the process.

**Comment by c0sm1n87** [comment]
[fixed](https://github.com/MachoThemes/MedZone/commit/9aba37cba43de177201b2dfc9929f5632939f216)
