### ISSUE TITLE
Hook for saving content backup

### ISSUE THREAD

**Issue by justintadlock** [MachoThemes/epsilon-framework#44]
Currently, content is saved here [reference](https://github.com/MachoThemes/epsilon-framework/blob/master/classes/class-epsilon-content-backup.php#L82):

```
add_action( 'customize_register', array( $this, 'backup_settings' ), 999 );
```

That means that the page content is never stored until the customizer is reloaded.  Instead, use the `customize_save_after` hook.  

Note that I've successfully tested this in a small test project.  Here's some sample code from that to give you an idea of how I handled the save callback:

```
add_action( 'customize_save_after', array( $this, 'save_page' ) );

public function save_page( $wp_customize ) {

	$blocks = array();

	$contents = $array_of_setting_names;

	foreach ( $contents as $content ) {

		$blocks[] = $this->format_text_block( $wp_customize->get_setting( $content )->value() );
	}

	$output = join( "\n\n", $blocks );

	wp_update_post(
		array(
			'ID'           => $this->front_page_id,
			'post_content' => $output
		)
	);
}
```

**Comment by c0sm1n87** [comment]
[fixed](https://github.com/MachoThemes/epsilon-framework/blob/customizer-improvements/classes/class-epsilon-content-backup.php#L86)

**Comment by justintadlock** [comment]
@cristianraiber wanted me to particularly check this out.  The changes you have in the framework work well for me.  It's much better than the previous hook used.

**Comment by cristianraiber** [comment]
@justintadlock - thanks for checking this :) :+1:
