### ISSUE TITLE
Use the front page, not a backup page

### ISSUE THREAD

**Issue by justintadlock** [MachoThemes/epsilon-framework#45]
When creating a front page editor, you already have everything you need.  There's no need to create an additional "backup" page.

Let the user choose their front page.  Then, get that page ID via `get_option( 'page_on_front' )`.

Some of the benefits to this:

* You don't have to create the page.
* You don't have to worry about making sure it stays in `draft` status.
* If the user switches themes, the content that they've created is already there on the front page until they choose to do something different.

**Comment by cristianraiber** [comment]
@justintadlock - just a quick thought about this. Wouldn't "overtaking" the content of the front-page be considered problematic, if the user decides to add content to this page in the old fashioned way? 

I know the TRT has been forcing people to show the front-page's content on the  ... well, front end.

**Comment by justintadlock** [comment]
This one is just an opinion of my own and shouldn't be taken as gospel.  There's some advantages/disadvantages to either option.  I'm going to leave this to y'all.  Just consider the above an alternative opinion.

I wouldn't have an issue _overtaking_ the content in this case (particularly if hiding the editor as mentioned in #46).

Also, no reviewer from the TRT should be forcing the front page's content to be shown when the theme author goes with a custom front page template.

**Comment by justintadlock** [comment]
I just want to note that the idealist in me still wants to shoot for using the chosen front page.  But, the realist in me realizes that a _backup_ page can save some headaches.  After seeing the work that y'all have put into this thing overall, I find myself thinking it's best to keep this as is for now.
