### ISSUE TITLE
Hide the editor

### ISSUE THREAD

**Issue by justintadlock** [MachoThemes/epsilon-framework#46]
On the edit page screen, in addition to the notice, the theme should hide the editor so that the user cannot edit the page content.

You should be able to do this with the following code:

```
add_action( 'edit_form_after_title', 'epsilon_disable_front_page_editor' );

function epsilon_disable_front_page_editor( $post ) {

	if ( get_option( 'page_on_front' ) == $post->ID )
		remove_post_type_support( $post->post_type, 'editor' );
}
```

Of course, change `get_option( 'page_on_front' )` to a function for getting your "backup" page ID if that's the route you choose.

You'd only want to hide it in production.  Obviously, you'd want to view it during development.

**Comment by c0sm1n87** [comment]
[fixed](https://github.com/MachoThemes/epsilon-framework/blob/customizer-improvements/classes/class-epsilon-content-backup.php#L119)
