### ISSUE TITLE
Formatting backup page content

### ISSUE THREAD

**Issue by justintadlock** [MachoThemes/epsilon-framework#48]
When storing the page content, you need to go all out.  This is what will make a huge difference between me (or another reviewer) seeing this feature as "working **with** the guidelines" vs. "working **around** the guidelines".

When formatting the content in the post, format it like you actually care if the user is able to edit it in the future or have it display reasonably if they switch away from your theme.

I'm only going to list some examples.  It's up to you to take it all the way.

### Spacing between sections

Currently, this is what it looks like when you have one section after another:

```
<!-- /Accordion Section -->
<!-- Testimonials Section -->
```

Simple fix would be:

```
<!-- /Accordion Section -->

<!-- Testimonials Section -->
```

It's a small detail, but it matters.

### Gutenberg format 

While Gutenberg is not final yet, perhaps it wouldn't hurt to follow in their footsteps with the HTML comments.

This section:

```
<!-- Testimonials Section -->
```

Might become:

```
<!-- epsilon/testimonials -->
```

Or, something along those lines.  I think namespacing like that here would just better prepare you for potential things in the future.

### Testimonial

Currently, a testimonial is stored like this:

```
<!-- Testimonials -->
Testimonial Title
Testimonial Subtitle
I've been using Members on nearly every site I've built over the past 5 years or so, especially if there are multiple users on a site. Members does what it's supposed to do, without any problems.

Now this update comes out - much improved UI, option to assign multiple roles per user, option to group capabilities by posts/pages/media/plugins/etc, and other improvements.
<img src="http://localhost/wp-content/uploads/2017/07/IMG_20170715_170728.jpg" />
<!-- /Testimonials-->
```

Give me something like:

```
<!-- Testimonials -->
<h2 class="testimonial-title">Testimonial Title</h2>
<h3 class="testimonial-subtitle">Testimonial Subtitle</h3>

<blockquote>
<p>I've been using Members on nearly every site I've built over the past 5 years or so, especially if there are multiple users on a site. Members does what it's supposed to do, without any problems.</p>

<p>Now this update comes out - much improved UI, option to assign multiple roles per user, option to group capabilities by posts/pages/media/plugins/etc, and other improvements.</p>
</blockquote>

<img src="http://localhost/wp-content/uploads/2017/07/IMG_20170715_170728.jpg" />
<!-- /Testimonials-->
```

### Doctors

Currently, doctors look like:

```
<!-- Doctors -->
Dr. Jonathan Doe
Surgeon
<p>Pellentesque dapibus tristique ornare. Quisque vitanimate viverra lorem. animatenean luctus lorem mi, et lobortis turpis porttitor ut. Donec dictum dolor varius metus pellentesque, quis elementum massa varius.</p>
http://facebook.com
http://twitter.com
<!-- /Doctors-->
```

Instead, go with something like:

```
<!-- Doctors -->
<h2 class="doctor-name">Dr. Jonathan Doe</h2>

<p class="doctor-specialty">Surgeon</p>

<p>Pellentesque dapibus tristique ornare. Quisque vitanimate viverra lorem. animatenean luctus lorem mi, et lobortis turpis porttitor ut. Donec dictum dolor varius metus pellentesque, quis elementum massa varius.</p>

<ul class="doctor-social">
<li><a href="http://facebook.com">Facebook</a></li>
<li><a href="http://twitter.com">Twitter</a></li>
</ul>
<!-- /Doctors-->
```

**Comment by c0sm1n87** [comment]
Thanks for the feedback @justintadlock,

I've created a condition to check in theme "files" for an override of that particular content "generation" so themes can setup their own rules. 

The backup (semantics) content class will check if class exists ( {ThemeName}_post_parser ) and if in this class a rule to parse the value for a certain ID is present ( parse_ . field_id() ).

This opens up a whole lot of room to create the blocks as we "need" them .. maybe when we're changing to the "customizer page builder" we`ll have the actual content generated "on save" rather on generating it every time a page loads. 

However, I think this is a good start that can be improved later on.

**Comment by justintadlock** [comment]
I like what you've done here.  Allowing it to be handled from the theme makes a lot of sense.  I know it was quite a bit of work, but you have a ton of flexibility now.  Good job.
