### ISSUE TITLE
Front-page sections panel should be styled like widgets

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/epsilon-framework#55]
Our design:

---

![image](https://user-images.githubusercontent.com/7841556/30424054-63a486ec-994d-11e7-9d29-698b5e53b0b6.png)

---

Widgets panel design:

---

![image](https://user-images.githubusercontent.com/7841556/30424030-4fd75d06-994d-11e7-814b-71e9cb4ccb04.png)

**Comment by c0sm1n87** [comment]
I don`t know if we need/should take this route. Our repeatable sections are entirely different from widgets and should not be "treated/compared" with

**Comment by cristianraiber** [comment]
We need more UI/UX expertise on this one. @ngabyn - care to step in?

**Comment by ngabyn** [comment]
Am jonglat si eu un pic : 

![image](https://user-images.githubusercontent.com/113568/31217560-08d9ac78-a9c0-11e7-97ab-ba008866f3c5.png)

Eu nu le-as face sa arate fix ca widgeturile dar am cateva sugestii:

- culoarea pinului de expand sa fie copiata de la cel din widgets
- iconul cu 3 bare are si o semnificatie de mutat in unele locuri si parca da' si o semnificatie de bara longitudinala gen sectiune 👍 
- numele din fata nu au neaparat o utilitate pentru utilizator, daca dorim sa avem chestia asta in spate e ceva necesar si ok
- marginea din dreapta e variabila, la mine era de 7 px la cristi pare de 2, as face fiecare element dintr-o parte in cealalta

**Comment by cristianraiber** [comment]
@ngabyn @c0sm1n87 - mie-mi place ce-a desenat @ngabyn - mergem pe asta?

**Comment by cristianraiber** [comment]
@c0sm1n87 - cand ii facem un release asteia?

**Comment by c0sm1n87** [comment]
Due by November 1, 2017 0% complete 👍
