### ISSUE TITLE
Misc JS enhancements 

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/epsilon-framework#56]
- [x] Currently, it's possible to expand as many sections as we want. Normal behavior should prevent this and collapse a previously expanded section when trying to expand a new one. See how widgets behave when trying to expand more than one
- [x] Clicking on the panel's back arrow (`.customize-section-back`) should close the `.doubled-section-parent` sidebar 
- [x] Clicking inside the section repeater panel (while the `.doubled-section-parent` panel is opened) should close the sidebar. See how widgets panel handles this.

**Comment by cristianraiber** [comment]
Here's one of the scenarios that can happen with the current panel implementation:

![image](https://user-images.githubusercontent.com/7841556/30425832-0e698776-9953-11e7-9728-ea3eb3aff3a9.png)

**Comment by c0sm1n87** [comment]
Clicking inside the section repeater panel (while the .doubled-section-parent panel is opened) should close the sidebar. See how widgets panel handles this. <-- asta nu o vad ca o necesitate, poti sa navighezi mai usor prin "content" daca nu se inchide sidebarul ( mai ales ca poti da click din greseala in timp ce creezi continutul ).  In scenariul atasat, alea sunt simple butoane care in afara de un click .. nu au alta actiune

**Comment by cristianraiber** [comment]
E un pic ciudat UX-ul asa. Daca deschid o alta sectiune, m-as astepta sa mi se inchida panel-ul precedent, asociat sectiunii pe care-o aveam deschisa inainte, si sa mi se deschida panel-ul aferent sectiunii noi. 

@ngabyn - avem nevoie de inca o parere aici pt. a hotari ce facem UI/UX wise.

**Comment by ngabyn** [comment]
Eu zic sa inchidem orice sidebar de-al nostru in orice scenariu ce cauzeaza un section overlay nu de alta da' nu ne ajuta prea mult in forma asta si arata mai mult a bug.

**Comment by cristianraiber** [comment]
Ele nu mai fac overlap, dar faptul ca panel-ul de adaugat elemente ramane deschis, desi eu am expandat o sectiune careia nu-i este subordonat respectivul panel, mie mi se pare ciudat. D'asta si sugeram sa facem ca la Widgets.

**Comment by ngabyn** [comment]
Deacord...  un sidebar ramane deschis cat panoul asociat cu actiunile din stanga e deschis.

**Comment by cristianraiber** [comment]
@c0sm1n87 - se pare ca s-a votat :)

**Comment by cristianraiber** [comment]
gj @c0sm1n87
