### ISSUE TITLE
Different width & styles for `doubled-section-parent`

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/epsilon-framework#57]
Widgets panel design:
---

![image](https://user-images.githubusercontent.com/7841556/30423760-88ed1f0a-994c-11e7-8db8-2d6d17db564a.png)

---

What we have: 

![image](https://user-images.githubusercontent.com/7841556/30423852-d111ea0e-994c-11e7-89ee-38ffbc97085a.png)

**Comment by cristianraiber** [comment]
- [ ] sidebar max-width: 300px
- [ ] close button changed
- [ ] background for repeater fields should be #EEE and not #FFF 
- [ ] panel title font changes 
- [ ] "add new entries" button is missing the CSS class `button`

**Comment by c0sm1n87** [comment]
![capture](https://user-images.githubusercontent.com/10389279/31081048-387669aa-a793-11e7-8d45-f19de17fe50d.JPG)

sidebar max 300px  is way too small for this

**Comment by c0sm1n87** [comment]
"add new entries" button is missing the CSS class .button <-- does it need it ? 😄
