### ISSUE TITLE
Handle blog page

### ISSUE THREAD

**Issue by c0sm1n87** [MachoThemes/epsilon-framework#68]
At the current moment, epsilon creates a control even for the blog page.
-> we need to "hide" controls by active callback
-> or integrate it somehow ( maybe allow addition of sections after the blog, e.g. -> adding a newsletter section afterwards or some other specific block )

**Comment by cristianraiber** [comment]
How about a filter added to this? I think the same issue will apply to WooCommerce pages and many more others. We should allow devlopers to use something like a filter to selct pages to be ignored.

**Comment by c0sm1n87** [comment]
or a custom field in the backend ( when editing the page ) so we can allow the "end user", not only devs, to select what pages should be "edited" by the customizer

**Comment by cristianraiber** [comment]
@ngabyn I still think it’s a good idea to automatically filter known pages, like Woo generated pages, Events calendar, EDD.

**Comment by ngabyn** [comment]
Dap, filtrarea automata a paginilor cunoscute + un filtru acccesibil developerilor ar fi o idee buna
