### ISSUE TITLE
Edit page screen in the admin

### ISSUE THREAD

**Issue by justintadlock** [MachoThemes/epsilon-framework#69]
Like the "front page" when viewed in the admin, I'd like to the other pages edited via the customizer given the same or similar treatment.

At the top of the page, let's get a notice that's something like:

```
This page contains content created by the customizer.  <a href="#">Edit In Customizer &rarr;</a>
```

Then, you need to decide if you're going to allow the user to edit from that screen.  If so, your notice should also explain that it will overwrite their customizations.  If not, I'd disable the editor on this screen.

**Comment by cristianraiber** [comment]
@justintadlock - this has been implemented, here: https://github.com/MachoThemes/epsilon-framework/commit/5236e98ec13a13db29af9af32ac2e9843114776c
