### ISSUE TITLE
Mixed-up show/hide icons

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/epsilon-framework#75]
![image](https://user-images.githubusercontent.com/7841556/32613209-f19f98e6-c572-11e7-9a1e-8cf0c909769e.png)

---

The "hidden" icon (top right of the notification) is currently highlighted which I believe is wrong.

**Comment by cristianraiber** [comment]
I think: https://github.com/MachoThemes/epsilon-framework/pull/65 is related to this issue

**Comment by c0sm1n87** [comment]
This is controlled by the theme welcome screen, not by epsilon. i`ll check the recommended actions from the customizer and change it
