### ISSUE TITLE
[Question] - Plugin version?

### ISSUE THREAD

**Issue by norewp** [MachoThemes/epsilon-framework#80]
Hello team,

First all, many many thanks for making this - totally awesome it is :)

I've been toying with the idea of adopting the framework be as an installable plugin for my projects rather than a theme drop in library - just wanted to touch base to see if you guys are not already working on or have one done already?

Would hate to end up with duplicity and conflict implementation.

Kind regards,
Zulfikar Nore

**Comment by c0sm1n87** [comment]
Hello,

Allowing epsilon-framework run from a plugin (just drop in your plugin and initiate it) is on our to-do list. Unfortunately, I can't give you an exact deadline .. but it should be available in the next release.
