### ISSUE TITLE
When new item added filters resetting on section

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/epsilon-framework#85]
Scenariu de testare:

1. asa arata sectiunea cu items
![image](https://user-images.githubusercontent.com/113568/37158288-b2b90480-22f3-11e8-98c0-7b113bb3031e.png)

2. adaug un item nou:
![image](https://user-images.githubusercontent.com/113568/37158330-d25d0692-22f3-11e8-9965-36eac686c02a.png)

3. orice schimbare in noul item sterge filtrul
![image](https://user-images.githubusercontent.com/113568/37158405-fdd71ce0-22f3-11e8-810f-86ef0ff0cb3f.png)

4. se pare ca toate sectiunile de acelasi tip isi pierd filtrul
![image](https://user-images.githubusercontent.com/113568/37158504-34cb356a-22f4-11e8-8e10-28ccef42bb1a.png)

**Comment by cristianraiber** [comment]
This has been fixed in the latest Epsilon rewrite. kudos @c0sm1n87
